### ISSUE TITLE
parseFile file nicht verwendet

### ISSUE THREAD

**Issue by timroesner** [duglah/SpotifyAccesstokenGetter#1]
https://github.com/duglah/SpotifyAccesstokenGetter/blob/daa4df18ccce34e55fd99fd6dbd5fbcc14f7ff89/index.js#L106

'code.html' sollte mit file ersetzt werden

**Comment by pmanstein** [comment]
Mit https://github.com/duglah/SpotifyAccesstokenGetter/commit/907b4f7eae5a696b6f0ba884467e4e157e44dff9 gefixt. Danke 👍
